//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ClientOrder = new HashSet<ClientOrder>();
            this.Insurance = new HashSet<Insurance>();
            this.Sales = new HashSet<Sales>();
            this.Supply = new HashSet<Supply>();
            this.Attributes = new HashSet<Attributes>();
        }
    
        public int Id { get; set; }
        public int IdCarType { get; set; }
        public int IdModel { get; set; }
        public int IdEngine { get; set; }
        public int IdBodywork { get; set; }
        public int IdEquipment { get; set; }
        public int IdColor { get; set; }
        public int IdCountry { get; set; }
        public string Vin { get; set; }
        public double Cost { get; set; }
        public double AddCost { get; set; }
        public Nullable<double> Sum { get; set; }
        public string ImagePath { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Bodywork Bodywork { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrder> ClientOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance> Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
        public virtual Color Color { get; set; }
        public virtual CountryOfAssembly CountryOfAssembly { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Model Model { get; set; }
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attributes> Attributes { get; set; }
    }
}
