//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrder
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdTransport { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Status Status { get; set; }
    }
}
