//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultations
    {
        public int Id { get; set; }
        public string Person_Name { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
