//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnRoadEntities : DbContext
    {
        public OnRoadEntities()
            : base("name=OnRoadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddService> AddService { get; set; }
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<Bodywork> Bodywork { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarType> CarType { get; set; }
        public virtual DbSet<ClientOrder> ClientOrder { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Consultations> Consultations { get; set; }
        public virtual DbSet<CountryOfAssembly> CountryOfAssembly { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engine> Engine { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Positon> Positon { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
