//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Id { get; set; }
        public int IdSupplier { get; set; }
        public System.DateTime DateIn { get; set; }
        public int IdTransport { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
